-- 创建 posts 表（存储发布的动态）
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    code TEXT,
    code_type TEXT DEFAULT 'python',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建 post_files 表（存储关联的文件）
CREATE TABLE IF NOT EXISTS post_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_post_files_post_id ON post_files(post_id);

-- 启用 Row Level Security (可选，用于生产环境)
-- ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE post_files ENABLE ROW LEVEL SECURITY;

-- 创建 policies (可选，根据需求调整)
-- CREATE POLICY "Anyone can view posts" ON posts FOR SELECT USING (true);
-- CREATE POLICY "Only authenticated can insert" ON posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');
-- CREATE POLICY "Anyone can view files" ON post_files FOR SELECT USING (true);
-- CREATE POLICY "Only authenticated can insert files" ON post_files FOR INSERT WITH CHECK (auth.role() = 'authenticated');